POST http://127.0.0.1:5000/api/v1/user
Content-Type: application/json

{
    "login": "my_login",
    "password": "qwerty",
    "email": "my_mail@mail.com",
    "name": "Steave",
    "last_name": "Jobs"
}

### 

GET http://127.0.0.1:5000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg5MjQwNzM2LCJpYXQiOjE3ODkyMzcxMzZ9.CwvF485BFtXbxOQTGpCkAWBJ-_4q4DUxf8zH-MFKcZU

###

POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "login": "my_login",
    "password": "qwerty"
}

###

POST http://127.0.0.1:5000/api/v1/ads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg5MjQwNzM2LCJpYXQiOjE3ODkyMzcxMzZ9.CwvF485BFtXbxOQTGpCkAWBJ-_4q4DUxf8zH-MFKcZU

{
    "title": "Ad #1"
}

###

POST http://127.0.0.1:5000/api/v1/ads
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg5MjQwNzM2LCJpYXQiOjE3ODkyMzcxMzZ9.CwvF485BFtXbxOQTGpCkAWBJ-_4q4DUxf8zH-MFKcZU

{
    "title": "Ad #2"
}

###

GET http://127.0.0.1:5000/api/v1/ads

###

GET http://127.0.0.1:5000/api/v1/ads/1

###

PATCH http://127.0.0.1:5000/api/v1/ads/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg5MjQwNzM2LCJpYXQiOjE3ODkyMzcxMzZ9.CwvF485BFtXbxOQTGpCkAWBJ-_4q4DUxf8zH-MFKcZU

{
    "title": "new title Ad #1",
    "description": "very good item"
}

###

PUT http://127.0.0.1:5000/api/v1/ads/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg5MjQwNzM2LCJpYXQiOjE3ODkyMzcxMzZ9.CwvF485BFtXbxOQTGpCkAWBJ-_4q4DUxf8zH-MFKcZU

{
    "title": "new title Ad #1"
}

###

DELETE http://127.0.0.1:5000/api/v1/ads/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzg5MjQwNzM2LCJpYXQiOjE3ODkyMzcxMzZ9.CwvF485BFtXbxOQTGpCkAWBJ-_4q4DUxf8zH-MFKcZU


