POST http://127.0.0.1:5000/api/v1/user
Content-Type: application/json

{
    "login": "my_login",
    "password": "qwerty",
    "email": "my_mail@mail.com",
    "name": "Steave",
    "last_name": "Jobs"
}

### 

GET http://127.0.0.1:5000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzg5MTU3OTkyLCJpYXQiOjE3ODkxNTQzOTJ9.Hxi9nP8PS3oJF3hy1PW9IkfYQ-FikFDnHu0ix9BUMeQ

###

POST http://127.0.0.1:5000/login
Content-Type: application/json

{
    "login": "my_login",
    "password": "qwerty"
}

###

POST http://127.0.0.1:5000/api/v1/ads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzg5MTU3OTkyLCJpYXQiOjE3ODkxNTQzOTJ9.Hxi9nP8PS3oJF3hy1PW9IkfYQ-FikFDnHu0ix9BUMeQ
Content-Type: application/json

{
    "title": "Ad #1"
}

###

POST http://127.0.0.1:5000/api/v1/ads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzg5MTU3OTkyLCJpYXQiOjE3ODkxNTQzOTJ9.Hxi9nP8PS3oJF3hy1PW9IkfYQ-FikFDnHu0ix9BUMeQ
Content-Type: application/json

{
    "title": "Ad #2"
}

###

GET http://127.0.0.1:5000/api/v1/ads

###

GET http://127.0.0.1:5000/api/v1/ads/9

###

PATCH http://127.0.0.1:5000/api/v1/ads/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzg5MTU3OTkyLCJpYXQiOjE3ODkxNTQzOTJ9.Hxi9nP8PS3oJF3hy1PW9IkfYQ-FikFDnHu0ix9BUMeQ
Content-Type: application/json

{
    "title": "new title Ad #1",
    "description": "very good item"
}

###

PUT http://127.0.0.1:5000/api/v1/ads/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzg5MTU3OTkyLCJpYXQiOjE3ODkxNTQzOTJ9.Hxi9nP8PS3oJF3hy1PW9IkfYQ-FikFDnHu0ix9BUMeQ
Content-Type: application/json

{
    "title": "new title Ad #1"
}

###

DELETE http://127.0.0.1:5000/api/v1/ads/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiZXhwIjoxNzg5MTU3OTkyLCJpYXQiOjE3ODkxNTQzOTJ9.Hxi9nP8PS3oJF3hy1PW9IkfYQ-FikFDnHu0ix9BUMeQ


